
var fs = require('fs');
var winston = require('winston');

exports.menu = require('./menu');
exports.meshconfig = require('./meshconfig');
exports.datasource = require('./datasource');
exports.db = require('./db');

exports.admin = {
    //web server port
    port: 12052,
    host: "0.0.0.0",

    //authentication service public key to verify jwt token generated by it
    jwt: {
        pub: fs.readFileSync('/opt/mca/auth/api/config/auth.pub'),
    }
};

exports.pub = {
    //web server port
    port: 12053,
    host: "0.0.0.0",
    
    //profile service api
    profile_api: 'http://localhost:12402',
    
    //jwt needed to access profile service - use auth/bin/auth.js to create the token
    profile_jwt: fs.readFileSync(__dirname+'/profile.jwt'),
};

exports.logger = {
    winston: {
        transports: [
            //display all logs to console
            new winston.transports.Console({
                timestamp: function() {
                    var d = new Date();
                    return d.toString(); 
                },
                level: 'debug',
                colorize: true
            }),
            
            /*
            //store all warnings / errors in error.log
            new (winston.transports.File)({ 
                filename: 'error.log',
                level: 'warn'
            })
            */
        ]
    },
    
    /*
    //logfile to store all requests (and its results) in json
    request: {
        transports: [
            new (winston.transports.File)({ 
                filename: 'request.log',
                json: true
            })
        ]
    }
    */
}


