
var fs = require('fs');
var winston = require('winston');

exports.menu = require('./menu');
exports.meshconfig = require('./meshconfig');
exports.datasource = require('./datasource');
exports.logger = require('./logger');
exports.db = require('./db');

exports.admin = {
    //web server port
    port: 12052,
    //host: "0.0.0.0",

    //authentication service public key to verify jwt token generated by it
    jwt: {
        pub: fs.readFileSync('/opt/mca/auth/api/config/auth.pub'),
    },
   
    //file to let other services know that mcadmin has finished db sync / migration
    readyfile: '/tmp/mcadmin.ready',
};

exports.pub = {
    //web server port
    port: 12053,
    //host: "0.0.0.0",
};

exports.common = {
    //profile service api
    profile_api: 'http://localhost:12402',
    //jwt needed to access profile service - use auth/bin/auth.js to create the token
    profile_jwt: fs.readFileSync(__dirname+'/profile.jwt'),
};


