
Alias /pwa/shared/ /home/grigutis/src/psconfig-web/api/config/shared/
Alias /pwa/ /home/grigutis/src/psconfig-web/ui/

ProxyPass "/pwa/api/pwa/" "http://localhost:8080/"
ProxyPass "/pwa/profiles/" "http://localhost:8081/"

<Directory /home/grigutis/src/psconfig-web/ui>
    Options Indexes FollowSymLinks

    AllowOverride None

    Require all granted
</Directory>
