"""empty message

Revision ID: 3007bc16556f
Revises: 66b4b6116412
Create Date: 2022-09-14 19:46:37.178096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3007bc16556f'
down_revision = '66b4b6116412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('group_id', sa.BigInteger(), nullable=False))
    op.add_column('tasks', sa.Column('schedule_id', sa.BigInteger(), nullable=True))
    op.add_column('tasks', sa.Column('test_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('tasks_group_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_schedule_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_test_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'schedules', ['schedule_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'tests', ['test_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'groups', ['group_id'], ['id'])
    op.drop_column('tasks', 'group')
    op.drop_column('tasks', 'schedule')
    op.drop_column('tasks', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('test', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('schedule', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('group', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_test_fkey', 'tasks', 'tests', ['test'], ['id'])
    op.create_foreign_key('tasks_schedule_fkey', 'tasks', 'schedules', ['schedule'], ['id'])
    op.create_foreign_key('tasks_group_fkey', 'tasks', 'groups', ['group'], ['id'])
    op.drop_column('tasks', 'test_id')
    op.drop_column('tasks', 'schedule_id')
    op.drop_column('tasks', 'group_id')
    # ### end Alembic commands ###
