-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.address_classes
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    data_source character varying COLLATE pg_catalog."default" NOT NULL,
    match_filter jsonb,
    exclude_filter jsonb,
    _meta jsonb,
    CONSTRAINT address_classes_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.addresses
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    address character varying COLLATE pg_catalog."default" NOT NULL,
    host bigint,
    labels jsonb,
    remote_addresses jsonb,
    lead_bind_address character varying COLLATE pg_catalog."default",
    pscheduler_address character varying COLLATE pg_catalog."default",
    tags character varying[] COLLATE pg_catalog."default",
    disabled boolean,
    no_agent boolean,
    _meta jsonb,
    CONSTRAINT addresses_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.addresses_contexts
(
    addresses_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    contexts_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT addresses_contexts_pkey PRIMARY KEY (addresses_id, contexts_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.archives
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    archiver character varying COLLATE pg_catalog."default" NOT NULL,
    data jsonb NOT NULL,
    transform jsonb,
    ttl interval,
    _meta jsonb,
    CONSTRAINT archives_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.contexts
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    context character varying COLLATE pg_catalog."default" NOT NULL,
    data jsonb NOT NULL,
    _meta jsonb,
    CONSTRAINT contexts_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.groups
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    default_address_label character varying COLLATE pg_catalog."default",
    unidirectional boolean,
    type character varying COLLATE pg_catalog."default" NOT NULL,
    excludes_self character varying COLLATE pg_catalog."default",
    excludes jsonb,
    _meta jsonb,
    CONSTRAINT list_groups_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.groups_address_classes
(
    groups_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address_classes_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    b_address boolean,
    CONSTRAINT groups_address_classes_pkey PRIMARY KEY (groups_id, address_classes_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.groups_addresses
(
    groups_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    addresses_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    b_address boolean,
    CONSTRAINT groups_addresses_pkey PRIMARY KEY (groups_id, addresses_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.hosts
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    tags character varying[] COLLATE pg_catalog."default",
    no_agent boolean,
    disabled boolean,
    _meta jsonb,
    CONSTRAINT hosts_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.hosts_archives
(
    hosts_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    archives_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT hosts_archives_pkey PRIMARY KEY (hosts_id, archives_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.schedules
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    start character varying COLLATE pg_catalog."default",
    slip interval,
    sliprand boolean,
    repeat interval,
    until character varying COLLATE pg_catalog."default",
    max_runs integer,
    _meta jsonb,
    CONSTRAINT schedules_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.subtasks
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    test bigint NOT NULL,
    schedule_offset jsonb,
    disabled boolean,
    tools character varying[] COLLATE pg_catalog."default",
    reference jsonb,
    _meta jsonb,
    CONSTRAINT subtasks_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.subtasks_archives
(
    subtasks_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    archives_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT subtasks_archives_pkey PRIMARY KEY (subtasks_id, archives_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.tasks
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    scheduled_by integer,
    "group" bigint NOT NULL,
    test bigint NOT NULL,
    schedule bigint,
    disabled boolean,
    tools character varying[] COLLATE pg_catalog."default",
    priority integer,
    reference jsonb,
    _meta jsonb,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.templates
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    includes character varying[] COLLATE pg_catalog."default",
    _meta jsonb,
    CONSTRAINT templates_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.templates_address_classes
(
    templates_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address_classes_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT templates_address_classes_pkey PRIMARY KEY (templates_id, address_classes_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.templates_addresses
(
    templates_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    addresses_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT templates_addresses_pkey PRIMARY KEY (templates_id, addresses_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.templates_archives
(
    templates_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    archives_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT templates_archives_pkey PRIMARY KEY (templates_id, archives_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.templates_contexts
(
    templates_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    contexts_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT templates_contexts_pkey PRIMARY KEY (templates_id, contexts_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.templates_groups
(
    templates_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    groups_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT templates_groups_pkey PRIMARY KEY (templates_id, groups_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.templates_hosts
(
    templates_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    hosts_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT templates_hosts_pkey PRIMARY KEY (templates_id, hosts_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.templates_schedules
(
    templates_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    schedules_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT templates_schedules_pkey PRIMARY KEY (templates_id, schedules_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.templates_subtasks
(
    templates_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    subtasks_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT templates_subtasks_pkey PRIMARY KEY (templates_id, subtasks_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.templates_tasks
(
    templates_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tasks_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT templates_tasks_pkey PRIMARY KEY (templates_id, tasks_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.templates_tests
(
    templates_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tests_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT templates_tests_pkey PRIMARY KEY (templates_id, tests_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.tests
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    type character varying COLLATE pg_catalog."default" NOT NULL,
    spec jsonb NOT NULL,
    _meta jsonb,
    CONSTRAINT tests_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

ALTER TABLE IF EXISTS public.addresses
    ADD CONSTRAINT addresses_host_fkey FOREIGN KEY (host)
    REFERENCES public.hosts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.addresses_contexts
    ADD CONSTRAINT addresses_contexts_addresses_id_fkey FOREIGN KEY (addresses_id)
    REFERENCES public.addresses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.addresses_contexts
    ADD CONSTRAINT addresses_contexts_contexts_id_fkey FOREIGN KEY (contexts_id)
    REFERENCES public.contexts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.groups_address_classes
    ADD CONSTRAINT groups_address_classes_address_classes_id_fkey FOREIGN KEY (address_classes_id)
    REFERENCES public.address_classes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.groups_address_classes
    ADD CONSTRAINT groups_address_classes_groups_id_fkey FOREIGN KEY (groups_id)
    REFERENCES public.groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.groups_addresses
    ADD CONSTRAINT groups_addresses_addresses_id_fkey FOREIGN KEY (addresses_id)
    REFERENCES public.addresses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.groups_addresses
    ADD CONSTRAINT groups_addresses_groups_id_fkey FOREIGN KEY (groups_id)
    REFERENCES public.groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.hosts_archives
    ADD CONSTRAINT hosts_archives_archives_id_fkey FOREIGN KEY (archives_id)
    REFERENCES public.archives (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.hosts_archives
    ADD CONSTRAINT hosts_archives_hosts_id_fkey FOREIGN KEY (hosts_id)
    REFERENCES public.hosts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.subtasks
    ADD CONSTRAINT subtasks_test_fkey FOREIGN KEY (test)
    REFERENCES public.tests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.subtasks_archives
    ADD CONSTRAINT subtasks_archives_archives_id_fkey FOREIGN KEY (archives_id)
    REFERENCES public.archives (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.subtasks_archives
    ADD CONSTRAINT subtasks_archives_subtasks_id_fkey FOREIGN KEY (subtasks_id)
    REFERENCES public.subtasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT tasks_group_fkey FOREIGN KEY ("group")
    REFERENCES public.groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT tasks_schedule_fkey FOREIGN KEY (schedule)
    REFERENCES public.schedules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT tasks_test_fkey FOREIGN KEY (test)
    REFERENCES public.tests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_address_classes
    ADD CONSTRAINT templates_address_classes_address_classes_id_fkey FOREIGN KEY (address_classes_id)
    REFERENCES public.address_classes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_address_classes
    ADD CONSTRAINT templates_address_classes_templates_id_fkey FOREIGN KEY (templates_id)
    REFERENCES public.templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_addresses
    ADD CONSTRAINT templates_addresses_addresses_id_fkey FOREIGN KEY (addresses_id)
    REFERENCES public.addresses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_addresses
    ADD CONSTRAINT templates_addresses_templates_id_fkey FOREIGN KEY (templates_id)
    REFERENCES public.templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_archives
    ADD CONSTRAINT templates_archives_archives_id_fkey FOREIGN KEY (archives_id)
    REFERENCES public.archives (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_archives
    ADD CONSTRAINT templates_archives_templates_id_fkey FOREIGN KEY (templates_id)
    REFERENCES public.templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_contexts
    ADD CONSTRAINT templates_contexts_contexts_id_fkey FOREIGN KEY (contexts_id)
    REFERENCES public.contexts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_contexts
    ADD CONSTRAINT templates_contexts_templates_id_fkey FOREIGN KEY (templates_id)
    REFERENCES public.templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_groups
    ADD CONSTRAINT templates_groups_groups_id_fkey FOREIGN KEY (groups_id)
    REFERENCES public.groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_groups
    ADD CONSTRAINT templates_groups_templates_id_fkey FOREIGN KEY (templates_id)
    REFERENCES public.templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_hosts
    ADD CONSTRAINT templates_hosts_hosts_id_fkey FOREIGN KEY (hosts_id)
    REFERENCES public.hosts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_hosts
    ADD CONSTRAINT templates_hosts_templates_id_fkey FOREIGN KEY (templates_id)
    REFERENCES public.templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_schedules
    ADD CONSTRAINT templates_schedules_schedules_id_fkey FOREIGN KEY (schedules_id)
    REFERENCES public.schedules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_schedules
    ADD CONSTRAINT templates_schedules_templates_id_fkey FOREIGN KEY (templates_id)
    REFERENCES public.templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_subtasks
    ADD CONSTRAINT templates_subtasks_subtasks_id_fkey FOREIGN KEY (subtasks_id)
    REFERENCES public.subtasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_subtasks
    ADD CONSTRAINT templates_subtasks_templates_id_fkey FOREIGN KEY (templates_id)
    REFERENCES public.templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_tasks
    ADD CONSTRAINT templates_tasks_tasks_id_fkey FOREIGN KEY (tasks_id)
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_tasks
    ADD CONSTRAINT templates_tasks_templates_id_fkey FOREIGN KEY (templates_id)
    REFERENCES public.templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_tests
    ADD CONSTRAINT templates_tests_templates_id_fkey FOREIGN KEY (templates_id)
    REFERENCES public.templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.templates_tests
    ADD CONSTRAINT templates_tests_tests_id_fkey FOREIGN KEY (tests_id)
    REFERENCES public.tests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;